### ISSUE TITLE
Help, HTTP over TCP.

### ISSUE THREAD

**Issue by ingnelson** [hauke96/tiny-http-proxy#5]
Hello @hauke96 
I am from America, is it  possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider , but any data the client need to transfer to the server should be via a new HTTP request ( encode64 ) then server decode the data  ? 
because my ISP provider blocks the upstream data via HTTP BODY.

It is difficul for me and i can not do it.
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your reply.

**Comment by hauke96** [comment]
I don't know if your ISP really blocks requests with an HTTP body, because it would be impossible for you to properly use the internet and e.g. create this github issue.

Your idea tunneling a HTTP request as base64 (or otherwise encoded) blob through a plain TCP connection would probably work, however it's way out of scope of this project. I would recommend you to create a new, blank project for this. But feel free to use this tiny-http-proxy as a base or to copy code from here (with respect to the apache 2 license).

**Comment by ingnelson** [comment]
@hauke96 I did a test to check the bytes size allow by the ISP provider by the http body : 

#on server:
`nc -l -n -p 80 | wc --bytes
`
#on client 
`for ((i=1;i<200;i++))  do dd if=/dev/zero bs=$i count=10; sleep 1 ; done | curl -s -X $'POST #blabla# HTTP/1.1\r\nX-Meta:' -T - -H 'Host:' -H 'User-Agent:' -H 'Accept:' -H 'Expect:' -H $'Trailer: 111\r\n ٌُُُُُُّّّّْْْْْْْْْْْْْْْْْْ\r\n\r\n' 172.245.22.211`


I found that the ISP block the connection  when the client upstream more than 50 bytes size.

Someone create a android app (plugin ) + shadowsocks  . That app client create a tunnel to the server , but when the client send or transfer any data to the server , it send it using a new HTTP request encoding the data on the URL or http header (example: base64  ) then the server decode it . The client doesn't use the body to upstream any data , this way the ISP provider do not blocks the connection .

Look: 
![IMG_20200903_141246_483](https://user-images.githubusercontent.com/6626845/92162546-94f0d800-edef-11ea-8c3f-774cbf401380.jpg)

This is the packet I captured using TCPDUMP:
[quantumnica1.zip](https://github.com/fangdingjun/sniproxy/files/5170965/quantumnica1.zip)

Could you create a client and server like that , please ? 
Me and many people would thank you, because the guy who created that android app sell to us a monthly account to have internet free.

Could you help us ? We really need it .

**Comment by hauke96** [comment]
I see the problem but again: This is not in the scope of this project and I can't help you with this. You already have the exact idea how this should world and I think it will. You also know at least some basic programming, so just take a programming language of your choice (I recommend python or go) and create such server. Again: Feel free to copy code from this repo.
